controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

random-by-month:
    path: /random/by-month/{year}
    controller: App\Controller\RandomApiController::showRandomByMonth
    requirements:
        month: '\d+'

random-by-year:
    path: /random/by-day/{month}
    controller: App\Controller\RandomApiController::showRandomByDay
    requirements:
        month: '([1-9]|1[0-2])'

#home:
#    path: /
#    controller: App\Controller\HomeController::index
